/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as ApiPublicThermisSplatRouteImport } from './routes/api/public/thermis/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicThermisSplatRoute = ApiPublicThermisSplatRouteImport.update({
  id: '/api/public/thermis/$',
  path: '/api/public/thermis/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/evaluation': typeof EvaluationRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/api/public/thermis/$': typeof ApiPublicThermisSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/evaluation': typeof EvaluationRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/api/public/thermis/$': typeof ApiPublicThermisSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRoute
  '/evaluation': typeof EvaluationRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/api/public/thermis/$': typeof ApiPublicThermisSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/evaluation'
    | '/events/$eventId'
    | '/api/public/thermis/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/evaluation'
    | '/events/$eventId'
    | '/api/public/thermis/$'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/evaluation'
    | '/events/$eventId'
    | '/api/public/thermis/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRoute
  EvaluationRoute: typeof EvaluationRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  ApiPublicThermisSplatRoute: typeof ApiPublicThermisSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/thermis/$': {
      id: '/api/public/thermis/$'
      path: '/api/public/thermis/$'
      fullPath: '/api/public/thermis/$'
      preLoaderRoute: typeof ApiPublicThermisSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRoute,
  EvaluationRoute: EvaluationRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  ApiPublicThermisSplatRoute: ApiPublicThermisSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
